version: "3.8"

services:
  location-backend:
    container_name: "location-backend"
    build:
      dockerfile: src/Locations.API/Dockerfile
      context: .
    ports:
      - 5217:80
    networks:
      - location
  
  location-frontend:
    container_name: "location-frontend"
    build:
      dockerfile: Dockerfile
      context: ./src/Mobile/
    ports:
      - 8100:8100
    depends_on:
      - location-backend
    networks:
      - location

  
networks:
  location:
    driver: bridge